### ISSUE TITLE
Add Command Aliases

### ISSUE THREAD

**Issue by mslevis** [AY2122S1-CS2103T-T09-1/tp#43]

**Comment by qreoct** [comment]
**Concept:** Aliases for commands are a shorthand way to invoke certain commands.

**Idea 1:** The program has pre-defined aliases for Command Words. 

e.g. instead of needing to type `edit`, the alias `e` will also parse to `edit`.

Possible syntax: `e spot/Bishan Library r/4` will be treated exactly the same way as `edit spot/Bishan Library r/4`

**Enhancement 1a:** The user can define their own aliases for Command Words. 

Possible syntax: `alias a/e c/edit` will set `e` to be an alias for `edit`.

Notes:
- Only allow Users to set aliases for valid Command Words
- Aliases themselves cannot be Command Words.
- Does there need to be an unalias command? What about edit alias?

**Idea 2:** The user can define their own aliases for Command fragments

e.g. User sets `myAlias` to mean `add r/5 t/cold`, which means running the command `myAlias n/Place` will result in `add r/5 t/cold n/Place`

Possible syntax: `alias a/myAlias c/"add r/5 t/cold"` will set `myAlias` to be an alias for the command fragment `add r/5 t/cold`.

Result: `Alias set!`

Notes:
- Be careful of recursion! Does this mean we disallow aliasing to other aliases? 
- Aliases themselves cannot be Command Words.
- Do not set the alias if User is attempting to create one for an invalid command fragment (?)
- Does there need to be an unalias command? What about edit alias?
